/*
 * This source file was generated by the Gradle 'init' task
 */
package tile.engine;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        Text message = new Text("Full message");
        StackPane root = new StackPane(message);

        Scene scene = new Scene(root, 400, 300);

        primaryStage.setTitle("Tile Engine");
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
