/*
 * This source file was generated by the Gradle 'init' task
 */
package tile.engine;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.layout.StackPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        Canvas canvas = new Canvas(256, 256);
        GraphicsContext gc = canvas.getGraphicsContext2D();

        int[][] tile = TileGenerator.generateGrassTile(4, 7);

        TileRenderer.renderTile(gc, tile, 12, 32, 32);

        primaryStage.setScene(new Scene(new StackPane(canvas)));
        primaryStage.setTitle("16x16 Generative Tile Demo");
        primaryStage.show();
    }
}
